service: serverless-jobcan-slack-api

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  environment:
    SLACK_TOKEN: ${env:SLACK_TOKEN}
    SLACK_CHANNEL: ${env:SLACK_CHANNEL}
  resourcePolicy:
    - Effect: Allow
      Principal: "*"
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*
      Condition:
        IpAddress:
          aws:SourceIp:
            - ${env:SOURCE_IP}

functions:
  jobcan_worktime:
    handler: handler.jobcanWorktime
    events:
      - http:
          path: jobcan
          method: get
  jobcan_touch:
    handler: handler.jobcanTouch
    events:
      - http:
          path: jobcan
          method: post
